# Loader Info
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
# Project Info
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://fpsmap.dubhe.dev/"
authors="${mod_authors}"
description='''${mod_description}'''
# Dependencies Info
[[dependencies.${mod_id}]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
